# Generated by Django 4.1 on 2022-10-14 02:20

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_useridtest'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserIdTest2',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('test', models.CharField(max_length=256)),
            ],
        ),
        migrations.AlterField(
            model_name='useridtest',
            name='_id',
            field=models.UUIDField(editable=False),
        ),
    ]
