# Generated by Django 4.1 on 2022-10-21 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_useridtest2_alter_useridtest__id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserIdTest',
        ),
        migrations.DeleteModel(
            name='UserIdTest2',
        ),
    ]
