# Generated by Django 4.1 on 2022-10-20 07:46

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('drf_house_test', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrfUsersSub',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('test', models.CharField(max_length=256)),
            ],
        ),
    ]
