# Generated by Django 4.1 on 2022-10-20 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf_house_test', '0004_drfuserssub2'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserIdTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.UUIDField(editable=False)),
                ('test', models.CharField(max_length=256)),
            ],
        ),
        migrations.DeleteModel(
            name='DrfUsersSub',
        ),
        migrations.DeleteModel(
            name='DrfUsersSub2',
        ),
    ]
