# Generated by Django 4.1 on 2022-10-20 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drf_house_test', '0005_useridtest_delete_drfuserssub_delete_drfuserssub2'),
    ]

    operations = [
    ]
