# Generated by Django 4.1 on 2022-10-21 00:59

from django.db import migrations, models
import djongo.models.fields
import drf_house_test.models


class Migration(migrations.Migration):

    dependencies = [
        ('drf_house_test', '0008_tablename'),
    ]

    operations = [
        migrations.CreateModel(
            name='Houses',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('house_id', models.CharField(max_length=256)),
                ('name', models.CharField(max_length=256)),
                ('address', djongo.models.fields.ArrayField(model_container=drf_house_test.models.Address)),
            ],
            options={
                'db_table': 'drf_houses',
            },
        ),
        migrations.DeleteModel(
            name='TableName',
        ),
        migrations.DeleteModel(
            name='TableTest',
        ),
        migrations.AlterModelTable(
            name='users',
            table='drf_users',
        ),
    ]
