# Generated by Django 4.1 on 2022-10-21 07:33

from django.db import migrations
import djongo.models.fields
import drf_house_test.models


class Migration(migrations.Migration):

    dependencies = [
        ('drf_house_test', '0009_houses_delete_tablename_delete_tabletest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='house',
            field=djongo.models.fields.ArrayField(default=[], model_container=drf_house_test.models.House),
        ),
    ]
