# Generated by Django 4.1 on 2022-10-23 00:26

from django.db import migrations
import djongo.models.fields
import drf_house_test.models


class Migration(migrations.Migration):

    dependencies = [
        ('drf_house_test', '0010_alter_users_house'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='house',
            field=djongo.models.fields.ArrayField(model_container=drf_house_test.models.House),
        ),
    ]
